-- ====================================================================
-- 페스티벌 스탬프 투어 및 통합 보안 관제 시스템 전체 DB 세팅 SQL
-- ====================================================================

-- 1. 기존 테이블 및 함수 정리 (초기화 필요 시 사용)
-- DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
-- DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
-- DROP FUNCTION IF EXISTS public.check_otp_and_stamp(TEXT, TEXT) CASCADE;
-- DROP FUNCTION IF EXISTS public.get_stamp_leaderboard(INT) CASCADE;
-- DROP FUNCTION IF EXISTS public.get_my_rank() CASCADE;
-- DROP FUNCTION IF EXISTS public.get_my_role() CASCADE;
-- DROP FUNCTION IF EXISTS public.get_my_club() CASCADE;
-- DROP TABLE IF EXISTS public.stamp_logs CASCADE;
-- DROP TABLE IF EXISTS public.stamps CASCADE;
-- DROP TABLE IF EXISTS public.clubs_status CASCADE;
-- DROP TABLE IF EXISTS public.users CASCADE;
-- DROP TABLE IF EXISTS public.clubs CASCADE;

-- ====================================================================
-- 2. 테이블 생성 (Tables DDL)
-- ====================================================================

-- 2.1 동아리/부스 목록 테이블
CREATE TABLE IF NOT EXISTS public.clubs (
    club_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2.2 사용자/운영진 프로필 테이블
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'L1' CHECK (role IN ('L1', 'L2', 'L3')),
    is_approved BOOLEAN NOT NULL DEFAULT true,
    club_id TEXT REFERENCES public.clubs(club_id),
    active_session_id TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2.3 부스별 실시간 OTP 및 상태 관리 테이블
CREATE TABLE IF NOT EXISTS public.clubs_status (
    club_id TEXT PRIMARY KEY REFERENCES public.clubs(club_id),
    current_otp TEXT,
    otp_expires_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ DEFAULT now()
);

-- 2.4 학생 스탬프 적립 내역 테이블
CREATE TABLE IF NOT EXISTS public.stamps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL,
    club_id TEXT NOT NULL REFERENCES public.clubs(club_id),
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT stamps_student_id_club_id_key UNIQUE (student_id, club_id)
);

-- 2.5 실시간 보안 감사 및 오류/시도 로그 테이블
CREATE TABLE IF NOT EXISTS public.stamp_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL,
    club_id TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2.6 대규모 랭킹 집계 고속화 인덱스
CREATE INDEX IF NOT EXISTS idx_stamps_ranking ON public.stamps(student_id, created_at);

-- ====================================================================
-- 3. RLS 헬퍼 함수 정의 (Security Definer Functions)
-- ====================================================================

-- 3.1 현재 로그인 유저의 역할(Role) 조회 헬퍼
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS TEXT
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT role FROM public.users WHERE student_id = auth.jwt()->>'email' LIMIT 1;
$$;

-- 3.2 현재 로그인 유저의 담당 부스(club_id) 조회 헬퍼
CREATE OR REPLACE FUNCTION public.get_my_club()
RETURNS TEXT
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT club_id FROM public.users WHERE student_id = auth.jwt()->>'email' LIMIT 1;
$$;

-- ====================================================================
-- 4. 핵심 비즈니스 로직 함수 (RPC & Trigger)
-- ====================================================================

-- 4.1 OTP 만료/중복/권한 검증 및 스탬프 트랜잭션 적립 RPC
CREATE OR REPLACE FUNCTION public.check_otp_and_stamp(p_club_id TEXT, p_input_otp TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
    v_user_email TEXT;
    v_user_role TEXT;
    v_current_otp TEXT;
    v_expires_at TIMESTAMPTZ;
    v_already_exists INT;
BEGIN
    v_user_email := auth.jwt()->>'email';
    IF v_user_email IS NULL THEN
        RETURN 'ERROR_UNAUTHORIZED';
    END IF;

    -- L1 학생 권한 확인 (부스장/관리자 계정 적립 차단)
    SELECT role INTO v_user_role
    FROM public.users
    WHERE student_id = v_user_email;

    IF v_user_role IS NULL OR v_user_role != 'L1' THEN
        INSERT INTO public.stamp_logs (student_id, club_id, status)
        VALUES (v_user_email, p_club_id, 'ERROR_NOT_A_STUDENT');
        RETURN 'ERROR_NOT_A_STUDENT';
    END IF;

    -- 부스 OTP 및 만료시간 조회
    SELECT current_otp, otp_expires_at
    INTO v_current_otp, v_expires_at
    FROM public.clubs_status
    WHERE club_id = p_club_id;

    IF NOT FOUND OR v_current_otp IS NULL THEN
        INSERT INTO public.stamp_logs (student_id, club_id, status)
        VALUES (v_user_email, p_club_id, 'ERROR_WRONG_CODE');
        RETURN 'ERROR_WRONG_CODE';
    END IF;

    -- 1. OTP 코드 일치 검증
    IF v_current_otp != p_input_otp THEN
        INSERT INTO public.stamp_logs (student_id, club_id, status)
        VALUES (v_user_email, p_club_id, 'ERROR_WRONG_CODE');
        RETURN 'ERROR_WRONG_CODE';
    END IF;

    -- 2. 만료 시간 검증
    IF NOW() > v_expires_at THEN
        INSERT INTO public.stamp_logs (student_id, club_id, status)
        VALUES (v_user_email, p_club_id, 'ERROR_EXPIRED_CODE');
        RETURN 'ERROR_EXPIRED_CODE';
    END IF;

    -- 3. 중복 적립 검증
    SELECT COUNT(*) INTO v_already_exists
    FROM public.stamps
    WHERE student_id = v_user_email AND club_id = p_club_id;

    IF v_already_exists > 0 THEN
        INSERT INTO public.stamp_logs (student_id, club_id, status)
        VALUES (v_user_email, p_club_id, 'ALREADY_STAMPED');
        RETURN 'ALREADY_STAMPED';
    END IF;

    -- 정상 적립 처리 (트랜잭션)
    INSERT INTO public.stamps (student_id, club_id)
    VALUES (v_user_email, p_club_id);

    INSERT INTO public.stamp_logs (student_id, club_id, status)
    VALUES (v_user_email, p_club_id, 'SUCCESS');

    RETURN 'SUCCESS';
END;
$$;

-- 4.2 학생용 실시간 랭킹 리더보드 조회 RPC (개인정보 자동 마스킹 및 RLS 안전 우회)
CREATE OR REPLACE FUNCTION public.get_stamp_leaderboard(p_limit INT DEFAULT 20)
RETURNS TABLE (
    rank BIGINT,
    masked_student_id TEXT,
    masked_name TEXT,
    stamp_count BIGINT,
    last_stamp_at TIMESTAMPTZ
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    WITH ranked AS (
        SELECT 
            s.student_id,
            COUNT(s.id) AS stamp_count,
            MAX(s.created_at) AS last_stamp_at,
            DENSE_RANK() OVER (ORDER BY COUNT(s.id) DESC, MAX(s.created_at) ASC) AS rank
        FROM public.stamps s
        GROUP BY s.student_id
    )
    SELECT 
        r.rank,
        -- 학번 마스킹 (예: 20101 -> 201**, 긴 형식의 경우 앞 3글자 + **)
        CASE 
            WHEN LENGTH(SPLIT_PART(r.student_id, '@', 1)) >= 4 THEN
                CONCAT(SUBSTRING(SPLIT_PART(r.student_id, '@', 1) FROM 1 FOR 3), '**')
            ELSE
                CONCAT(SUBSTRING(SPLIT_PART(r.student_id, '@', 1) FROM 1 FOR 1), '**')
        END AS masked_student_id,
        -- 이름 마스킹 (예: 홍길동 -> 홍*동, 이산 -> 이*)
        CASE 
            WHEN LENGTH(COALESCE(u.name, '')) >= 3 THEN 
                CONCAT(SUBSTRING(u.name FROM 1 FOR 1), '*', SUBSTRING(u.name FROM 3))
            WHEN LENGTH(COALESCE(u.name, '')) = 2 THEN 
                CONCAT(SUBSTRING(u.name FROM 1 FOR 1), '*')
            ELSE COALESCE(u.name, '참가자')
        END AS masked_name,
        r.stamp_count,
        r.last_stamp_at
    FROM ranked r
    LEFT JOIN public.users u ON u.student_id = r.student_id
    ORDER BY r.rank ASC
    LIMIT p_limit;
$$;

-- 4.3 학생 본인 순위 조회 RPC
CREATE OR REPLACE FUNCTION public.get_my_rank()
RETURNS TABLE (
    rank BIGINT,
    stamp_count BIGINT
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    WITH ranked AS (
        SELECT 
            s.student_id,
            COUNT(s.id) AS stamp_count,
            MAX(s.created_at) AS last_stamp_at,
            DENSE_RANK() OVER (ORDER BY COUNT(s.id) DESC, MAX(s.created_at) ASC) AS rank
        FROM public.stamps s
        GROUP BY s.student_id
    )
    SELECT 
        r.rank,
        r.stamp_count
    FROM ranked r
    WHERE r.student_id = auth.jwt()->>'email'
    LIMIT 1;
$$;

-- 4.4 Supabase Auth 회원가입 시 users 테이블 자동 동기화 트리거 함수 (L2도 즉시 승인)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  INSERT INTO public.users (id, student_id, name, role, is_approved, club_id)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', '사용자'),
    COALESCE(NEW.raw_user_meta_data->>'role', 'L1'),
    true, -- 학생(L1) 및 부스(L2) 모두 기본 승인 처리
    NEW.raw_user_meta_data->>'club_id'
  )
  ON CONFLICT (student_id) DO UPDATE SET
    name = EXCLUDED.name,
    role = EXCLUDED.role,
    is_approved = true;
  RETURN NEW;
END;
$$;

-- 4.5 auth.users 트리거 바인딩
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ====================================================================
-- 5. Row Level Security (RLS) 정책 설정
-- ====================================================================

-- 5.1 clubs
ALTER TABLE public.clubs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "clubs_select_all" ON public.clubs;
CREATE POLICY "clubs_select_all" ON public.clubs
  FOR SELECT TO public USING (true);

-- 5.2 users
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "users_insert_policy" ON public.users;
DROP POLICY IF EXISTS "users_select_policy" ON public.users;
DROP POLICY IF EXISTS "users_update_policy" ON public.users;

CREATE POLICY "users_insert_policy" ON public.users
  FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "users_select_policy" ON public.users
  FOR SELECT TO public USING (
    (get_my_role() = 'L3') OR (student_id = (auth.jwt() ->> 'email'))
  );

CREATE POLICY "users_update_policy" ON public.users
  FOR UPDATE TO public USING (
    (get_my_role() = 'L3') OR (student_id = (auth.jwt() ->> 'email'))
  );

-- 5.3 clubs_status
ALTER TABLE public.clubs_status ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "clubs_status_select" ON public.clubs_status;
DROP POLICY IF EXISTS "clubs_status_upsert" ON public.clubs_status;

CREATE POLICY "clubs_status_select" ON public.clubs_status
  FOR SELECT TO public USING (true);

CREATE POLICY "clubs_status_upsert" ON public.clubs_status
  FOR ALL TO public USING (
    (get_my_role() = 'L3') OR (club_id = get_my_club())
  );

-- 5.4 stamps
ALTER TABLE public.stamps ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "stamps_insert_policy" ON public.stamps;
DROP POLICY IF EXISTS "stamps_select_policy" ON public.stamps;

CREATE POLICY "stamps_insert_policy" ON public.stamps
  FOR INSERT TO public WITH CHECK (
    (student_id = (auth.jwt() ->> 'email')) OR (get_my_role() = 'L3')
  );

CREATE POLICY "stamps_select_policy" ON public.stamps
  FOR SELECT TO public USING (
    (get_my_role() = 'L3') OR 
    ((get_my_role() = 'L2') AND (club_id = get_my_club())) OR 
    (student_id = (auth.jwt() ->> 'email'))
  );

-- 5.5 stamp_logs
ALTER TABLE public.stamp_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "stamp_logs_insert_policy" ON public.stamp_logs;
DROP POLICY IF EXISTS "stamp_logs_select_policy" ON public.stamp_logs;

CREATE POLICY "stamp_logs_insert_policy" ON public.stamp_logs
  FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "stamp_logs_select_policy" ON public.stamp_logs
  FOR SELECT TO public USING (
    get_my_role() = 'L3'
  );

-- ====================================================================
-- 6. RPC 권한 부여 (Grants)
-- ====================================================================
GRANT EXECUTE ON FUNCTION public.get_stamp_leaderboard(INT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_rank() TO authenticated;

-- ====================================================================
-- 7. Realtime Publication 설정
-- ====================================================================
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.users;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.stamps;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.stamp_logs;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END $$;

-- ====================================================================
-- 8. 기초 데이터 시드 (Initial Seed Data)
-- ====================================================================

-- 기본 부스 5개 등록 (위치 정보 포함, booth-01 형식으로 통일)
INSERT INTO public.clubs (club_id, name, location) VALUES
  ('booth-01', '컴퓨터공학과 로봇 부스', '공학관 1층 로비'),
  ('booth-02', '밴드부 버스킹 관람', '야외 잔디광장 버스킹존'),
  ('booth-03', '총학생회 굿즈 나눔', '학생회관 1층 나눔터'),
  ('booth-04', '요리동아리 타코야끼', '학생식당 앞 푸드존'),
  ('booth-05', '사진동아리 네컷사진', '중앙도서관 앞 포토존')
ON CONFLICT (club_id) DO UPDATE SET 
  name = EXCLUDED.name,
  location = EXCLUDED.location;
